import type { Priority } from "./priority";
import type { CategoryId } from "./categories";

export interface TopicMeta {
  slug: string;
  title: string;
  short?: string;
  category: CategoryId;
  priority: Priority;
  /** Häufigkeit in den letzten 12 Prüfungen (laut Auswertung „Häufigste Themen"), wenn erhoben. */
  frequencyPct?: number;
  /** Kumulierte Punkte aller AP2-Prüfungen seit 2020 (Quelle: it-berufe-podcast). */
  pointsAllTime?: number;
  /** Stichworte, die in Aufgaben häufig vorkommen. */
  keywords?: string[];
  /** Einzeiler, erscheint in Listen. */
  summary: string;
  /** Seit Prüfungskatalog Okt. 2024 neu oder deutlich verstärkt. */
  newSince2025?: boolean;
}

/**
 * Die Prioritäten basieren auf:
 *   - Auswertung der 12 letzten IHK-AP2-Prüfungen (PDF „Häufigste Themen")
 *   - Offiziellem Prüfungskatalog (IHK) für Fachinformatiker Anwendungsentwicklung
 *   - Berichten aus Foren / it-berufe-podcast / ap2.online
 */
export const topics: TopicMeta[] = [
  // ---------------- Algorithmen / Pseudocode ----------------
  {
    slug: "pseudocode",
    title: "Pseudocode",
    short: "Pseudocode schreiben & lesen",
    category: "algorithmen",
    priority: "essentiell",
    frequencyPct: 100,
    pointsAllTime: 317,
    keywords: ["Schleife", "Verzweigung", "Tracing", "Variable", "Funktion", "Schreibtischtest"],
    summary:
      "Algorithmen sprachunabhängig notieren – das häufigste Prüfungsthema überhaupt (100%). Der größte Einzel-Punktbringer der AP2.",
  },
  {
    slug: "kontrollstrukturen",
    title: "Kontrollstrukturen",
    category: "algorithmen",
    priority: "sehr-hoch",
    keywords: ["if", "while", "for", "switch", "break", "continue"],
    summary: "Sequenz, Verzweigung, Schleifen – Grundbausteine jeder Pseudocode-Aufgabe.",
  },
  {
    slug: "rekursion",
    title: "Rekursion",
    category: "algorithmen",
    priority: "mittel",
    keywords: ["Basisfall", "Stack", "Fakultät", "Fibonacci"],
    summary: "Funktion ruft sich selbst auf – Basisfall, Rekursionsfall, Vor- und Nachteile.",
  },
  {
    slug: "suchen-sortieren",
    title: "Such- und Sortieralgorithmen",
    category: "algorithmen",
    priority: "hoch",
    keywords: ["Bubblesort", "Selection Sort", "Insertion Sort", "Binärsuche", "O-Notation"],
    summary: "Lineare/Binäre Suche, Bubble-/Selection-/Insertion-Sort – explizit im Katalog seit 2025.",
    newSince2025: true,
  },

  // ---------------- Datenbanken / SQL ----------------
  {
    slug: "sql-grundlagen",
    title: "SQL – Grundlagen (DDL, DML, DQL, DCL, TCL)",
    category: "datenbanken",
    priority: "essentiell",
    frequencyPct: 100,
    pointsAllTime: 200,
    keywords: ["DDL", "DML", "DQL", "DCL", "TCL", "CRUD", "GRANT", "REVOKE"],
    summary: "SQL-Sprachkomponenten im Überblick – kommt in jeder Prüfung vor. DCL (GRANT/REVOKE) kam erstmals Sommer 2025.",
  },
  {
    slug: "sql-select",
    title: "SELECT-Abfragen",
    category: "datenbanken",
    priority: "essentiell",
    frequencyPct: 42,
    pointsAllTime: 155,
    keywords: ["WHERE", "JOIN", "GROUP BY", "HAVING", "ORDER BY", "Aggregat"],
    summary: "Daten lesen: WHERE, JOINs, Aggregation, Sortierung, Unterabfragen. Nach Pseudocode der zweitgrößte Punktbringer.",
  },
  {
    slug: "sql-joins",
    title: "JOINs & Unterabfragen",
    category: "datenbanken",
    priority: "sehr-hoch",
    keywords: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "Subquery"],
    summary: "Mehrere Tabellen verknüpfen – Stolperstein in fast jeder SELECT-Aufgabe.",
  },
  {
    slug: "sql-update",
    title: "UPDATE",
    category: "datenbanken",
    priority: "hoch",
    frequencyPct: 50,
    keywords: ["SET", "WHERE", "mehrere Spalten"],
    summary: "Datensätze gezielt ändern – halbe Prüfungen haben ein UPDATE-Statement.",
  },
  {
    slug: "sql-insert",
    title: "INSERT",
    category: "datenbanken",
    priority: "mittel",
    frequencyPct: 25,
    keywords: ["VALUES", "INSERT INTO … SELECT"],
    summary: "Neue Datensätze anlegen. Syntax und Besonderheiten (Auto-ID, NULL).",
  },
  {
    slug: "sql-delete",
    title: "DELETE",
    category: "datenbanken",
    priority: "niedrig",
    frequencyPct: 17,
    keywords: ["WHERE", "TRUNCATE"],
    summary: "Daten löschen – inkl. Abgrenzung zu TRUNCATE und Foreign-Key-Folgen.",
  },
  {
    slug: "sql-ddl",
    title: "DDL: CREATE, ALTER, DROP",
    category: "datenbanken",
    priority: "mittel",
    keywords: ["PRIMARY KEY", "FOREIGN KEY", "NOT NULL", "UNIQUE"],
    summary: "Tabellen und Constraints anlegen und ändern – häufig Teil der Datenbankaufgabe.",
  },
  {
    slug: "relationales-datenmodell",
    title: "Relationales Datenmodell",
    category: "datenbanken",
    priority: "sehr-hoch",
    frequencyPct: 75,
    pointsAllTime: 141,
    keywords: ["Tabelle", "Primärschlüssel", "Fremdschlüssel", "Relation"],
    summary: "Vom Szenario zum Tabellenschema – Top-4-Thema in den letzten Prüfungen.",
  },
  {
    slug: "erm",
    title: "ER-Modell (ERM)",
    category: "datenbanken",
    priority: "hoch",
    frequencyPct: 50,
    pointsAllTime: 68,
    keywords: ["Entität", "Beziehung", "Kardinalität", "Crow's Foot", "Chen-Notation", "Min-Max"],
    summary: "Konzeptuelles Datenmodell mit Entitäten, Beziehungen und Kardinalitäten.",
  },
  {
    slug: "normalisierung",
    title: "Normalisierung (1NF–3NF)",
    category: "datenbanken",
    priority: "hoch",
    keywords: ["Anomalien", "Atomarität", "funktionale Abhängigkeit", "Transitivität"],
    summary: "Redundanzen beseitigen und Anomalien vermeiden – klassische Klausurfrage.",
  },
  {
    slug: "transaktionen-acid",
    title: "Transaktionen & ACID",
    category: "datenbanken",
    priority: "mittel",
    keywords: ["Atomicity", "Consistency", "Isolation", "Durability", "Deadlock"],
    summary: "ACID-Prinzipien und was sie in Schieflagen (Deadlock, Rollback) bedeuten.",
  },
  {
    slug: "nosql",
    title: "NoSQL-Datenbanken",
    category: "datenbanken",
    priority: "mittel",
    keywords: ["Key-Value", "Dokument", "Spalte", "Graph", "CAP", "BASE"],
    summary: "Alternative Datenbank-Typen, CAP-Theorem und BASE-Prinzip.",
  },
  {
    slug: "sql-injection",
    title: "SQL Injection & Gegenmaßnahmen",
    category: "datenbanken",
    priority: "mittel",
    keywords: ["Prepared Statement", "Escaping", "Validierung"],
    summary: "Wie Angriffe funktionieren und wie man sie mit Prepared Statements verhindert.",
  },

  // ---------------- UML ----------------
  {
    slug: "klassendiagramm",
    title: "Klassendiagramm",
    category: "uml",
    priority: "sehr-hoch",
    frequencyPct: 83,
    pointsAllTime: 79,
    keywords: ["Attribute", "Methoden", "Sichtbarkeit", "Vererbung", "Assoziation", "Multiplizität"],
    summary: "Statische Sicht auf eine OO-Anwendung – in 83% der Prüfungen gefragt.",
  },
  {
    slug: "aktivitaetsdiagramm",
    title: "Aktivitätsdiagramm",
    category: "uml",
    priority: "sehr-hoch",
    frequencyPct: 92,
    pointsAllTime: 130,
    keywords: ["Start", "Ende", "Entscheidung", "Fork", "Join", "Swimlane"],
    summary: "Abläufe visualisieren – das häufigste UML-Diagramm in der AP2 (92%).",
  },
  {
    slug: "sequenzdiagramm",
    title: "Sequenzdiagramm",
    category: "uml",
    priority: "hoch",
    frequencyPct: 58,
    pointsAllTime: 64,
    keywords: ["Lebenslinie", "Nachricht", "Aktivierung", "synchron", "asynchron"],
    summary: "Zeitlicher Nachrichtenaustausch zwischen Objekten.",
  },
  {
    slug: "zustandsdiagramm",
    title: "Zustandsdiagramm",
    category: "uml",
    priority: "mittel",
    frequencyPct: 33,
    pointsAllTime: 61,
    keywords: ["Zustand", "Transition", "Ereignis", "Guard"],
    summary: "Zustände und Zustandsübergänge eines Objekts.",
  },
  {
    slug: "anwendungsfalldiagramm",
    title: "Anwendungsfalldiagramm (Use Case)",
    category: "uml",
    priority: "mittel",
    keywords: ["Akteur", "Use Case", "include", "extend"],
    summary: "Systemgrenzen, Akteure und Anwendungsfälle – oft in Analysephasen.",
  },
  {
    slug: "komponenten-verteilungsdiagramm",
    title: "Komponenten- & Verteilungsdiagramm",
    category: "uml",
    priority: "niedrig",
    keywords: ["Komponente", "Interface", "Node", "Deployment"],
    summary: "Struktur- und Einsatzsicht auf ein System – selten, aber möglich.",
  },

  // ---------------- Objektorientierung ----------------
  {
    slug: "oo-grundprinzipien",
    title: "OO-Grundprinzipien",
    category: "uml",
    priority: "sehr-hoch",
    frequencyPct: 75,
    keywords: ["Abstraktion", "Kapselung", "Vererbung", "Polymorphie"],
    summary: "Die 4 Säulen der Objektorientierung – regelmäßig in MC- und Theoriefragen.",
  },
  {
    slug: "klassen-objekte",
    title: "Klassen & Objekte",
    category: "uml",
    priority: "hoch",
    keywords: ["Attribut", "Methode", "Konstruktor", "Instanz"],
    summary: "Bausteine der OO-Programmierung und wie sie sich zum Klassendiagramm verhalten.",
  },
  {
    slug: "klassenbeziehungen",
    title: "Klassenbeziehungen",
    category: "uml",
    priority: "hoch",
    keywords: ["Vererbung", "Assoziation", "Aggregation", "Komposition"],
    summary: "Vererbung, Assoziation, Aggregation, Komposition – mit Diamantnotation.",
  },
  {
    slug: "generics",
    title: "Generische Klassen",
    category: "uml",
    priority: "niedrig",
    keywords: ["Template", "Type Parameter"],
    summary: "Typparameter, Templates – vorwiegend in Sprachvergleichen.",
  },

  // ---------------- Programmiersprachen ----------------
  {
    slug: "paradigmen",
    title: "Programmierparadigmen",
    category: "programmierung",
    priority: "mittel",
    keywords: ["imperativ", "deklarativ", "funktional", "OO", "prozedural"],
    summary: "Imperativ, deklarativ, funktional, objektorientiert – wann passt was?",
  },
  {
    slug: "typisierung-compiler",
    title: "Typisierung & Übersetzung",
    category: "programmierung",
    priority: "mittel",
    keywords: ["statisch", "dynamisch", "Compiler", "Interpreter", "JIT"],
    summary: "Statisch/dynamisch, stark/schwach, Compiler vs. Interpreter.",
  },
  {
    slug: "datenstrukturen",
    title: "Datenstrukturen",
    category: "programmierung",
    priority: "mittel",
    keywords: ["Array", "Liste", "Stack", "Queue", "Baum", "Hashmap"],
    summary: "Array, Liste, Stack, Queue, Baum, Hashmap – Eigenschaften und Einsatz.",
  },
  {
    slug: "fehlerbehandlung",
    title: "Fehlerbehandlung & Exceptions",
    category: "programmierung",
    priority: "mittel",
    keywords: ["try", "catch", "finally", "throw", "Exit-Code"],
    summary: "Exceptions, try/catch/finally, Exit-Codes und Debugging-Grundlagen.",
  },
  {
    slug: "nebenlaeufigkeit",
    title: "Nebenläufigkeit",
    category: "programmierung",
    priority: "niedrig",
    keywords: ["Thread", "Race Condition", "async", "synchron", "parallel"],
    summary: "Synchron, asynchron, parallel – Grundbegriffe und Fallstricke.",
  },
  {
    slug: "no-low-code",
    title: "No-Code & Low-Code",
    category: "programmierung",
    priority: "niedrig",
    keywords: ["visuelle Entwicklung", "Bürger-Entwickler"],
    summary: "Neu im Katalog: No-/Low-Code-Plattformen – Chancen und Grenzen.",
  },

  // ---------------- Prozesse & Neuerungen 2025 ----------------
  {
    slug: "bpmn",
    title: "BPMN 2.0",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Pool", "Lane", "Event", "Gateway", "Task"],
    summary: "Geschäftsprozess-Notation – hat Struktogramm und PAP im Katalog 2025 ersetzt.",
    newSince2025: true,
  },
  {
    slug: "ki-grundlagen",
    title: "KI-Grundlagen",
    category: "programmierung",
    priority: "mittel",
    keywords: ["Machine Learning", "Trainingsdaten", "LLM", "generative KI", "Bias"],
    summary: "ML-Konzepte, generative KI, Chancen und Risiken – neu im Katalog 2025.",
    newSince2025: true,
  },
  {
    slug: "green-it",
    title: "Nachhaltigkeit & Green IT",
    category: "prozesse",
    priority: "mittel",
    keywords: ["Energieeffizienz", "PUE", "Ressourcen", "Nachhaltigkeit"],
    summary: "Energieeffizienz, Ressourcenverbrauch, nachhaltige Entwicklung – neu im Katalog 2025.",
    newSince2025: true,
  },
  {
    slug: "tdd",
    title: "Test-Driven Development (TDD)",
    category: "qualitaet",
    priority: "mittel",
    keywords: ["Red-Green-Refactor", "Unit-Test zuerst"],
    summary: "Red-Green-Refactor-Zyklus: erst der Test, dann der Code. Neu im Katalog.",
    newSince2025: true,
  },
  {
    slug: "last-performance-tests",
    title: "Last- und Performance-Tests",
    category: "qualitaet",
    priority: "mittel",
    keywords: ["Lasttest", "Stresstest", "Skalierbarkeit", "Durchsatz"],
    summary: "Nichtfunktionale Tests unter Last – explizit im Katalog seit 2025.",
    newSince2025: true,
  },

  // ---------------- Qualität & Testen ----------------
  {
    slug: "qualitaetssicherung",
    title: "Qualitätssicherung",
    category: "qualitaet",
    priority: "mittel",
    keywords: ["ISO 25010", "Wartbarkeit", "Zuverlässigkeit", "KVP"],
    summary: "Qualitätsmerkmale (ISO 25010), Maßnahmen, kontinuierliche Verbesserung.",
  },
  {
    slug: "teststufen",
    title: "Teststufen",
    category: "qualitaet",
    priority: "mittel",
    keywords: ["Unit", "Integration", "System", "Abnahme"],
    summary: "Unit-, Integrations-, System- und Abnahmetest – V-Modell-Sichtweise.",
  },
  {
    slug: "testmethoden",
    title: "Testmethoden",
    category: "qualitaet",
    priority: "mittel",
    keywords: ["Black Box", "White Box", "Graybox", "Regression"],
    summary: "Black-, White-, Graybox-Tests und was sie jeweils prüfen.",
  },
  {
    slug: "unit-tests-coverage",
    title: "Unit-Tests & Code-Coverage",
    category: "qualitaet",
    priority: "mittel",
    frequencyPct: 33,
    keywords: ["C0", "C1", "Zweigabdeckung", "Anweisungsabdeckung"],
    summary: "Was bedeutet welche Coverage-Stufe? Kleine Rechenaufgaben sind beliebt.",
  },
  {
    slug: "testautomatisierung",
    title: "Testautomatisierung & CI",
    category: "qualitaet",
    priority: "niedrig",
    keywords: ["CI/CD", "Pipeline", "Continuous Testing"],
    summary: "Automatisierte Tests und Continuous-Testing in modernen Pipelines.",
  },

  // ---------------- Sicherheit & Datenschutz ----------------
  {
    slug: "schutzziele",
    title: "Schutzziele der IT-Sicherheit",
    category: "sicherheit",
    priority: "hoch",
    keywords: ["Vertraulichkeit", "Integrität", "Verfügbarkeit", "Authentizität"],
    summary: "VIV(A)-Schutzziele – regelmäßig in Multiple-Choice-Fragen.",
  },
  {
    slug: "angriffe",
    title: "Typische Angriffe",
    category: "sicherheit",
    priority: "hoch",
    keywords: ["Phishing", "DoS", "Man-in-the-Middle", "XSS", "CSRF"],
    summary: "Phishing, DoS/DDoS, MITM, XSS, CSRF, Ransomware – kennen und abgrenzen.",
  },
  {
    slug: "kryptografie",
    title: "Kryptografie",
    category: "sicherheit",
    priority: "mittel",
    keywords: ["symmetrisch", "asymmetrisch", "Hash", "TLS", "Zertifikat"],
    summary: "Symmetrisch/asymmetrisch, Hashing, TLS – mit kleiner Rechnung möglich.",
  },
  {
    slug: "dsgvo",
    title: "DSGVO & Datenschutz",
    category: "sicherheit",
    priority: "hoch",
    keywords: ["Zweckbindung", "Datenminimierung", "Betroffenenrechte", "TOM"],
    summary: "Grundsätze der DSGVO, Betroffenenrechte, Pflichten von Unternehmen.",
  },
  {
    slug: "backup-archivierung",
    title: "Backup vs. Archivierung",
    category: "sicherheit",
    priority: "mittel",
    keywords: ["Vollbackup", "inkrementell", "differenziell", "3-2-1"],
    summary: "Sicherungsarten, 3-2-1-Regel und Abgrenzung zur Archivierung.",
  },
  {
    slug: "authentifizierung",
    title: "Authentifizierung & Zugriffskontrolle",
    category: "sicherheit",
    priority: "mittel",
    keywords: ["MFA", "RBAC", "SSO", "OAuth", "RADIUS"],
    summary: "Faktoren, Rollen/Rechte, SSO-Verfahren.",
  },

  // ---------------- Netzwerk ----------------
  {
    slug: "osi-modell",
    title: "OSI-Modell",
    category: "netzwerk",
    priority: "mittel",
    keywords: ["Schichten", "TCP/IP", "Kapselung"],
    summary: "7-Schichten-Modell mit typischen Protokollen je Schicht.",
  },
  {
    slug: "ip-subnetting",
    title: "IP-Adressierung & Subnetting",
    category: "netzwerk",
    priority: "mittel",
    keywords: ["IPv4", "CIDR", "Subnetzmaske", "IPv6"],
    summary: "Netz-/Hostanteil, CIDR, Subnetzberechnungen (typische Rechenaufgabe).",
  },
  {
    slug: "protokolle",
    title: "Netzwerkprotokolle & Dienste",
    category: "netzwerk",
    priority: "mittel",
    keywords: ["HTTP", "DNS", "DHCP", "SMTP", "FTP"],
    summary: "Die wichtigsten Protokolle und ihre Ports.",
  },
  {
    slug: "topologien",
    title: "Netzwerk-Topologien",
    category: "netzwerk",
    priority: "niedrig",
    keywords: ["Stern", "Bus", "Ring", "Mesh"],
    summary: "Physische und logische Topologien im Vergleich.",
  },
  {
    slug: "vpn-wlan",
    title: "VPN, WLAN & VLAN",
    category: "netzwerk",
    priority: "niedrig",
    keywords: ["Site-to-Site", "Client-to-Site", "WPA3", "SSID"],
    summary: "Sichere Verbindungen und Netzsegmentierung.",
  },
  {
    slug: "cloud-speicher",
    title: "Speicherlösungen & Cloud",
    category: "netzwerk",
    priority: "mittel",
    keywords: ["SaaS", "PaaS", "IaaS", "FaaS", "DAS", "NAS", "SAN", "RAID"],
    summary: "Cloud-Modelle, Speicherarchitekturen, RAID-Level – ein Favorit für MC-Fragen.",
  },

  // ---------------- Software-Architektur ----------------
  {
    slug: "architektur-patterns",
    title: "Architektur-Patterns",
    category: "architektur",
    priority: "mittel",
    keywords: ["MVC", "Schichten", "Microservices", "Monolith", "Event-Driven"],
    summary: "MVC, Schichten, Microservices, Event-Driven – Vor- und Nachteile.",
  },
  {
    slug: "modularisierung",
    title: "Modularisierung",
    category: "architektur",
    priority: "niedrig",
    keywords: ["Kopplung", "Kohäsion", "Single Responsibility"],
    summary: "Kopplung und Kohäsion als Qualitätsmerkmale.",
  },
  {
    slug: "container",
    title: "Container-Technologien",
    category: "architektur",
    priority: "mittel",
    keywords: ["Docker", "Kubernetes", "Image", "Registry"],
    summary: "Container vs. VMs, Docker-Grundbegriffe, Orchestrierung.",
  },
  {
    slug: "design-patterns",
    title: "Design Patterns",
    category: "architektur",
    priority: "mittel",
    keywords: ["Singleton", "Factory", "Observer", "Strategy", "Adapter", "Iterator"],
    summary: "GoF-Patterns nach Kategorie – Erzeugungs-, Struktur-, Verhaltensmuster.",
  },

  // ---------------- Web & Schnittstellen ----------------
  {
    slug: "http",
    title: "HTTP: Methoden & Status-Codes",
    category: "web",
    priority: "hoch",
    keywords: ["GET", "POST", "PUT", "DELETE", "200", "301", "404", "500"],
    summary: "HTTP-Methoden, Idempotenz, wichtige Status-Codes – beliebt in MC-Fragen.",
  },
  {
    slug: "rest-apis",
    title: "REST-APIs",
    category: "web",
    priority: "hoch",
    keywords: ["Ressource", "JSON", "stateless", "Endpunkt"],
    summary: "Prinzipien einer REST-Schnittstelle und typische Endpunkt-Gestaltung.",
  },
  {
    slug: "soap-webservices",
    title: "SOAP & WSDL",
    category: "web",
    priority: "niedrig",
    keywords: ["XML", "WSDL", "Envelope"],
    summary: "Älterer Webservice-Standard – Abgrenzung zu REST kennen.",
  },
  {
    slug: "datenformate",
    title: "CSV, XML, JSON",
    category: "web",
    priority: "mittel",
    keywords: ["Parser", "Schema", "Validierung"],
    summary: "Austauschformate im Vergleich, typische Anwendungsfälle.",
  },
  {
    slug: "xml-validierung",
    title: "XML validieren (DTD, XSD)",
    category: "web",
    priority: "niedrig",
    keywords: ["wohlgeformt", "gültig", "DTD", "XSD"],
    summary: "Wohlgeformtheit vs. Gültigkeit, DTD vs. XSD.",
  },
  {
    slug: "web-sicherheit",
    title: "Sicherheit von Webanwendungen",
    category: "web",
    priority: "mittel",
    keywords: ["XSS", "CSRF", "SQLi", "OWASP Top 10", "CSP"],
    summary: "XSS, CSRF, SQLi und wie man sie verhindert (OWASP-Perspektive).",
  },

  // ---------------- Prozesse ----------------
  {
    slug: "vorgehensmodelle",
    title: "Vorgehensmodelle",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Wasserfall", "V-Modell", "Spiral", "agil", "Scrum", "Kanban"],
    summary: "Klassisch vs. agil – Vor-/Nachteile, wann passt was?",
  },
  {
    slug: "scrum",
    title: "Scrum-Grundlagen",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Product Owner", "Scrum Master", "Sprint", "Backlog", "Review"],
    summary: "Rollen, Artefakte, Events – ein Dauerbrenner in Theorie-Aufgaben.",
  },
  {
    slug: "versionsverwaltung",
    title: "Versionsverwaltung (Git)",
    category: "prozesse",
    priority: "mittel",
    keywords: ["Commit", "Branch", "Merge", "Pull Request", "Konflikt"],
    summary: "Zentral vs. verteilt, Git-Workflows, typische Kommandos.",
  },
  {
    slug: "anforderungen",
    title: "Anforderungsanalyse",
    category: "prozesse",
    priority: "mittel",
    keywords: ["funktional", "nicht-funktional", "Lastenheft", "Pflichtenheft"],
    summary: "Funktional/nicht-funktional, Lasten- vs. Pflichtenheft.",
  },
  {
    slug: "make-or-buy",
    title: "Eigenentwicklung vs. Fremdfertigung",
    category: "prozesse",
    priority: "niedrig",
    keywords: ["Make or Buy", "TCO", "Abhängigkeit"],
    summary: "Wann selbst entwickeln, wann kaufen? Kriterien und Bewertung.",
  },
  {
    slug: "projektphasen",
    title: "Projektphasen / Projektlebenszyklus",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Initiierung", "Planung", "Durchführung", "Überwachung", "Abschluss"],
    summary: "Die klassischen 4-5 Phasen eines Projekts – Basis jeder PM-Aufgabe.",
  },
  {
    slug: "netzplan",
    title: "Netzplantechnik & kritischer Pfad",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Vorgänger", "Nachfolger", "FAZ", "SAZ", "Pufferzeit", "kritischer Pfad"],
    summary: "Vorwärts-/Rückwärtsterminierung, Pufferzeiten, kritischer Pfad – beliebte Rechenaufgabe.",
  },
  {
    slug: "bedarfs-machbarkeitsanalyse",
    title: "Bedarfs- und Machbarkeitsanalyse",
    category: "prozesse",
    priority: "hoch",
    keywords: ["Bedarf", "Machbarkeit", "technisch", "wirtschaftlich", "rechtlich", "Stakeholder"],
    summary: "Was braucht der Kunde? Ist das Projekt machbar (technisch/wirtschaftlich/rechtlich)?",
  },
  {
    slug: "nutzwertanalyse",
    title: "Nutzwertanalyse",
    category: "prozesse",
    priority: "mittel",
    keywords: ["Kriterien", "Gewichtung", "Score", "Entscheidung"],
    summary: "Entscheidungen zwischen Alternativen mit gewichteten Kriterien strukturieren.",
  },
  {
    slug: "risikomanagement",
    title: "Risikomanagement",
    category: "prozesse",
    priority: "mittel",
    keywords: ["Risiko", "Eintrittswahrscheinlichkeit", "Schadenshöhe", "Risikomatrix", "Maßnahme"],
    summary: "Risiken identifizieren, bewerten (Risikowert = EW × Schaden), begegnen.",
  },

  // ---------------- Wirtschaft ----------------
  {
    slug: "wirtschaftlichkeitsanalyse",
    title: "Wirtschaftlichkeitsanalyse",
    category: "wirtschaft",
    priority: "hoch",
    keywords: ["Amortisation", "ROI", "Break-Even", "TCO", "Kapitalwert"],
    summary: "Amortisationsrechnung, ROI, Break-Even – prüft, ob sich ein Projekt finanziell lohnt.",
  },
  {
    slug: "kundenbeziehungen",
    title: "Kundenbeziehungen & CRM",
    category: "wirtschaft",
    priority: "niedrig",
    keywords: ["CRM", "Kundenbindung", "Relationship Marketing"],
    summary: "CRM als Konzept, Kundenbindung, Nachbereitung von Gesprächen.",
  },
  {
    slug: "recht",
    title: "Recht für ITler",
    category: "wirtschaft",
    priority: "mittel",
    keywords: ["Urheberrecht", "Markenrecht", "UWG", "Lizenz"],
    summary: "Urheber-, Namens-, Wettbewerbsrecht, typische Stolperfallen.",
  },
  {
    slug: "lizenzmodelle",
    title: "Lizenzmodelle",
    category: "wirtschaft",
    priority: "mittel",
    keywords: ["Open Source", "proprietär", "Copyleft", "GPL", "MIT"],
    summary: "Open-Source- vs. proprietäre Lizenzen, Copyleft-Effekte.",
  },
  {
    slug: "wiso-arbeitsrecht",
    title: "Arbeitsrecht & Ausbildung",
    category: "wirtschaft",
    priority: "hoch",
    keywords: ["BBiG", "Arbeitsvertrag", "Kündigung", "Arbeitszeitgesetz", "Urlaub"],
    summary: "Rechte/Pflichten Azubi ↔ Betrieb, Kündigungsarten, ArbZG – klassisch WiSo-MC.",
  },
  {
    slug: "wiso-sozialversicherung",
    title: "Sozialversicherung",
    category: "wirtschaft",
    priority: "hoch",
    keywords: ["Kranken", "Pflege", "Renten", "Arbeitslosen", "Unfall"],
    summary: "Die 5 Säulen und wer was zahlt – sehr beliebt in WiSo-MC.",
  },
  {
    slug: "wiso-bgb",
    title: "BGB & Verträge",
    category: "wirtschaft",
    priority: "hoch",
    keywords: ["Kaufvertrag", "Werkvertrag", "Dienstvertrag", "Willenserklärung", "Mangel", "Verzug"],
    summary: "Vertragsarten, Willenserklärung, Leistungsstörungen – Pflicht in WiSo.",
  },
  {
    slug: "wiso-rechtsformen",
    title: "Rechtsformen von Unternehmen",
    category: "wirtschaft",
    priority: "mittel",
    keywords: ["GmbH", "AG", "OHG", "KG", "UG", "GbR"],
    summary: "Personen- vs. Kapitalgesellschaften, Haftung, Mindestkapital.",
  },
  {
    slug: "wiso-mitbestimmung",
    title: "Tarif & Mitbestimmung",
    category: "wirtschaft",
    priority: "mittel",
    keywords: ["Tarifvertrag", "Betriebsrat", "Gewerkschaft", "JAV"],
    summary: "Tarifautonomie, Betriebsrat, Mitbestimmungsrechte.",
  },
  {
    slug: "wiso-wirtschaftsordnung",
    title: "Wirtschaftsordnung & Markt",
    category: "wirtschaft",
    priority: "mittel",
    keywords: ["Angebot", "Nachfrage", "Marktformen", "Preisbildung", "Wirtschaftskreislauf"],
    summary: "Marktmechanismen, Marktformen (Polypol, Oligopol, Monopol), Preisbildung.",
  },
  {
    slug: "wiso-nachhaltigkeit",
    title: "Nachhaltigkeit im Unternehmen",
    category: "wirtschaft",
    priority: "niedrig",
    keywords: ["Umweltschutz", "Nachhaltigkeit", "CSR"],
    summary: "Ökologisches, ökonomisches, soziales Handeln – neu verstärkt im Katalog 2025.",
    newSince2025: true,
  },

  // ---------------- Kommunikation ----------------
  {
    slug: "praesentieren",
    title: "Präsentieren & Visualisierung",
    category: "kommunikation",
    priority: "niedrig",
    keywords: ["7x7-Regel", "Storytelling", "Farbwirkung"],
    summary: "Präsentationstechnik, Foliengestaltung, Rhetorik.",
  },
  {
    slug: "usability",
    title: "Usability & UX",
    category: "kommunikation",
    priority: "niedrig",
    keywords: ["ISO 9241", "Dialoggrundsätze", "Accessibility"],
    summary: "Usability vs. UX, die 7 Dialoggrundsätze.",
  },
];

export function topicBySlug(slug: string): TopicMeta | undefined {
  return topics.find((t) => t.slug === slug);
}

export function topicsByCategory(categoryId: string): TopicMeta[] {
  return topics.filter((t) => t.category === categoryId);
}
